apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage  # 與 StorageClass 關聯
  local:
    path: /mnt/nfs/k3s-pv     # 指定本地目錄或磁碟的路徑
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - kafka-broker-03-tbb  # 指定該 PV 所屬的節點名稱

